#
# mruby/c  src/Makefile
#
# Copyright (C) 2015- Kyushu Institute of Technology.
# Copyright (C) 2015- Shimane IT Open-Innovation Center.
#
#  This file is distributed under BSD 3-Clause License.
#

TARGET = mrubyc

SRCS = alloc.c c_array.c c_hash.c c_math.c c_numeric.c \
	c_object.c c_range.c c_string.c class.c console.c error.c global.c \
	keyvalue.c load.c mrblib.c rrt0.c symbol.c value.c vm.c mrubyc.c \
	hal.c

include ../common.mk